const data = {
  products: [
    {
      name: 'iphone 14',
      slug: 'iphone-14',
      category: 'phone',
      image: '/images/phone1.png',
      price: 120000,
      countInStock: 10,
      brand: 'iphone',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality phone',
    },
    {
      name: 'Mote-G10 phone',
      slug: 'Moto-G10-phone',
      category: 'phone',
      image: '/images/phone2.png',
      price: 14000,
      countInStock: 0,
      brand: 'MOTO',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality phone',
    },
    {
      name: 'Samsung-S5-phone',
      slug: 'Samsung-S5-phone',
      category: 'phone',
      image: '/images/phone3.png',
      price: 13000,
      countInStock: 20,
      brand: 'Samsung',
      rating: 4.0,
      numReviews: 15,
      description: 'high quality phone',
    },
    {
      name: 'Oppo-Zenbook-phone',
      slug: 'Oppo-Zenbook-phone',
      category: 'phone',
      image: '/images/phone4.png',
      price: 45000,
      countInStock: 25,
      brand: 'Oppo',
      rating: 4.4,
      numReviews: 45,
      description: 'high quality phone',
    },
  ],
};

export default data;
