const data = {
  products: [
    {
      name: 'iphone 14',
      slug: 'iphone-14',
      category: 'phone',
      image: '/images/phone1.png',
      price: 999,
      countInStock: 10,
      brand: 'iphone',
      rating: 4.5,
      numReviews: 109,
      description: 'high quality phone',
    },
    {
      name: 'Mote-G10 phone',
      slug: 'Moto-G10-phone',
      category: 'phone',
      image: '/images/phone2.png',
      price: 500,
      countInStock: 15,
      brand: 'MOTO',
      rating: 4.5,
      numReviews: 148,
      description: 'high quality phone',
    },
    {
      name: 'Samsung-S5-phone',
      slug: 'Samsung-S5-phone',
      category: 'phone',
      image: '/images/phone3.png',
      price: 749,
      countInStock: 20,
      brand: 'Samsung',
      rating: 4.0,
      numReviews: 215,
      description: 'high quality phone',
    },
    {
      name: 'Oppo-Zenbook-phone',
      slug: 'Oppo-Zenbook-phone',
      category: 'phone',
      image: '/images/phone4.png',
      price: 450,
      countInStock: 25,
      brand: 'Oppo',
      rating: 4.4,
      numReviews: 145,
      description: 'high quality phone',
    },
    {
      name: 'iphone 13',
      slug: 'iphone-13',
      category: 'phone',
      image: '/images/phone5.png',
      price: 599,
      countInStock: 10,
      brand: 'iphone',
      rating: 4.4,
      numReviews: 140,
      description: 'high quality phone',
    },
    {
      name: 'iphone 11-pro',
      slug: 'iphone-11-pro',
      category: 'phone',
      image: '/images/phone6.png',
      price: 600,
      countInStock: 10,
      brand: 'iphone',
      rating: 4.7,
      numReviews: 200,
      description: 'high quality phone',
    },
  ],
};

export default data;
